services:
  DocProDB:
    image: postgres:18
    container_name: DocProDB
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - docprodb_data:/var/lib/postgresql/data

  docproapi:
    build: ./backend
    container_name: DocProAPI
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    environment:
      DATABASE_URL: postgresql://postgres:1234@DocProDB:5432/postgres
    depends_on:
      - DocProDB
    volumes:
      - ./backend:/app
      - ./backend/uploads:/app/uploads
    command: ["/bin/sh", "-c", "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000"]

volumes:
  docprodb_data: