[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "alembic upgrade head && gunicorn -k uvicorn.workers.UvicornWorker -w 2 -b app.main:app"
restartPolicyType = "on_failure"